= *Cahier des Charges - SAÉ 2.01/2.05*

== Daily Bank

Version 1.0, 10 Mai 2023, Groupe 3B1

Emilien FIEU, Vincent BARETTE, Tanguy PICUIRA

=== Présentation du sujet

Le sujet répond à la gestion des comptes bancaires, et des employés.
Une partie est déjà existante, le reste va devoir être développé.



== Analyse de l'existant

Aujourd'hui, la Version 0 de DailyBank permet :

* De modifier les informations d’un client
* De créer un nouveau client
* De consulter un compte
* De débiter un compte
* De rendre un compte inactif


image::img/usecasev0.svg[]

== Analyse des besoins

[plantuml]
....
include::plantUML/useCaseV1.puml[]
....

Le guichetier peut créditer ou débiter un compte à travers une base de données.

Le guichetier peut créer un compte bancaire.

Le guichetier peut effectuer un virement d'un compte bancaire à l'autre.

Le guichetier peut clôturer un compte bancire.

Le Chef d'Agence peut "gérer" les guichetiers, et le Chef d’Agence. _Cela signifie qu'il peut créer, lire, supprimer et mettre à jour les comptes des guichetiers et du Chef d'Agence._


== Contraintes

=== Contraintes techniques

Le projet doit être réalisé avec les languages de programmation Java et SQL. Une base de données Oracle est utilisée.

JavaFX est utilisé pour la création d'interfaces graphiques.

La documentation doit être réalisé en AsciiDoc.

Le Gantt doit être fournis au format PDF.

=== Contraintes organisationnelles

Le projet doit être réalisé avant le *mardi 16 mai 17h*, par une équipe de 3 personnes.

.*Semaine 19*
* Première version du cahier des charges en asciidoc
* Première version du GANTT en PDF

.*Semaine 20*
* Deuxième version du cahier des charges en asciidoc
* Deuxième version du GANTT en PDF
* Vérification du GANTT de la première semaine
* Première version du document *technique* et du document *utilisateur*
* Première version du cahier des tests
* Première version du JAR

.*Semaine 21*
* Vérification du GANTT de la deuxième semaine
* Deuxième version du document *technique* et du document *utilisateur*
* Chiffrage du projet
* Deuxième version du JAR
* Deuxième version du cahier des tests & recette finale

.*Semaine 22*
* Soutenance orale
* Evaluation individuelle

.*Semaine 23*
* Evaluation individuelle
