= Cahier De Recette - DailyBankApp
:toc:
:toc-position: preamble
:toc-title: Sommaire
:title-page:
:sectnums:
:stem: asciimath
:Entreprise: DailyBank
:Equipe:

* Tanguy Picuira
* Emilien Fieu
* Vincent Barette

Version 2.0, 26 Mai 2023, Groupe 3B1

== Introduction
=== Objet :
[.text-justify]
Ce document a été produit dans le cadre d'un projet d'élaboration d'une application bancaire pour DailyBank


== Pre-Requis :
[.text-justify]
L'exécution des tests spécifiés au chapitre suivant requiert :

* Une base de données installée (référence document technique).
* L'environnement de test tel que spécifié dans la partie "Environnement de test" de ce document.
* Les fiches de tests. *À vérifier*


=== Éléments à tester :
[.text-justify]
Les éléments testés concernent les Use-Cases spécifiées dans la *documentation technique*.


=== Environnement de test :
[.text-justify]
Ordinateur sous Windows ou OS équivalent.



== Cas de test :
=== Fonctionnalités des guichetiers :
==== Gestion des clients :

|====

>|Cas de test 4+|Test-01-01-01
>|Titre 4+|Création d'un nouveau client
>|Objectif 4+| Vérifier qu'il est possible de créer un nouveau client

5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.1 ^|Cliquer sur le bouton "Nouveau client". ^|La fenêtre de création des clients s'ouvre. ^| aucune ^|OK
^|All_G_C.2 ^|Compléter les champs spécifiés et valider. ^|Un nouveau client est créé. ^|aucune ^|OK


5+|

5+|Commentaire :
|====


|====

>|Cas de test 4+|Test-01-01-02
>|Titre 4+|Modification d'un client
>|Objectif 4+| Vérifier qu'il est possible de modifier un client

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.3 ^|Cliquer sur le bouton "Modifier client". ^|La fenêtre de modification des données du client s'ouvre. ^|Le client est sélectionné. ^|OK
^|All_G_C.4 ^|Modifier les champs souhaités et confirmer. ^|Retour sur les informations du client. Le client est modifié. ^|La fenêtre « modifier » client est active ^|OK
^|All_G_C.5 ^|Modifier les champs souhaités et annuler. ^|Retour sur les informations du client. Le client est inchangé. ^|La fenêtre « modifier » client est active ^|OK

|====


==== Gestion des comptes bancaires :


|====

>|Cas de test 4+|Test-01-02-03
>|Titre 4+|Consultation d'un compte
>|Objectif 4+| Vérifier qu'il est possible de consulter un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1 ^|Cliquer sur le bouton "Comptes client". ^|La page des comptes du client s’affiche. ^|Un client actif est sélectionné. ^|OK
^|All_G_CB.2 ^|Sélectionner le bouton "Voir opérations". ^|La page des opérations du compte s’affiche. ^|Un compte actif est sélectionné. ^|OK
^|All_G_CB.3 ^|Sélectionner le bouton "Clôturer compte". ^|Une alerte nous indiquant que le compte est clôturé s'affiche et le compte est en mode clôturé ^|Un compte actif est sélectionné. ^|OK


|====

|====

>|Cas de test 4+|Test-01-02-04
>|Titre 4+|Création d'un compte
>|Objectif 4+| Vérifier qu'il est possible de créer un compte

5+|

^|All_G_CB.4 ^|Sélectionner le bouton "Nouveau compte". ^|Une page s'ouvre qui nous permet de renseigner les informations du nouveau compte qui doit être créé ^|Le découvert autorisé doit être inférieur à 0. ^|OK

|====


==== Gestion des opérations :

|====

>|Cas de test 4+|Test-01-03-01
>|Titre 4+|Débiter un compte
>|Objectif 4+| Vérifier qu'il est possible de débiter un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.1 ^|Cliquer sur le bouton "Enregistrer Débit". ^|La page des débits du compte s’affiche. ^| Un compte actif est sélectionné. ^|OK
^|All_G_COP.2  ^|Rentrer un montant 50 dans le champ "Montant". ^|Le nouveau solde est +50euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros
^|OK
^|All_G_COP.3  ^|Rentrer un montant 150 dans le champ "Montant". ^|Le nouveau solde est -50 euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros, le découvert
autorisé est de -100 euros.
^|OK
^|All_G_COP.4  ^|Rentrer un montant 250 dans le champ "Montant". ^|Blocage ! + pop-up ^| Le compte sélectionné a un solde de +100 euros, le découvert
autorisé est de -100 euros.
^|OK



|====

==== Génération d’un relevé de compte :

|====
>|Cas de test 4+|Test-01-04-01
>|Titre 4+|Génération d’un relevé de compte
>|Objectif 4+| Vérifier qu'il est possible de générer un relevé de compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat

^|All_G_GRC.1 ^|Sélectionner un compte et cliquer sur le bouton « Générer relevé ». ^|Une page s'ouvre demandant la date du relevé ^|aucune ^|OK

^|All_G_GRC.2 ^|Rentrer une date et valider. ^|Une fenêtre de sélection de l’emplacement du relevé s’ouvre ^|La date n’est pas dans le futur ^|OK

^|All_G_GRC.3 ^|Sélectionner un emplacement et valider. ^|Le relevé est généré et enregistré à l’emplacement sélectionné ^|l’emplacement est valide ^|OK

|====

===  Fonctionnalités des chefs d'agence :
[.text-justify]
Les chefs d'agence ont accès aux mêmes fonctionnalités que les guichetiers, ainsi que d'autres qui leur sont réservées.

==== Gestion des clients :

|====
>|Cas de test 4+|Test-02-01-01
>|Titre 4+|Rendre inactif un client
>|Objectif 4+| Vérifier qu'il est possible de rendre un client inactif

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1    ^|Sélectionner le bouton "Inactif" et confirmer. ^|...  ^|Un client actif est sélectionné ... ^| ...

5+|

5+|Commentaire : REVOIR AVEC
*clôturés*.|
|====

==== Gestion des Employés

|====

>|Cas de test 4+|Test-02-02-01
>|Titre 4+| Ajouter un employé
>|Objectif 4+| Vérifier qu'il est possible de créer un nouvel employé

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_E.1    ^|Cliquer sur le bouton "Nouvel employé" ^|La fenêtre de création d’employé s’ouvre  ^|L’utilisateur est connecté en tant que chef d’agence ^| OK
^|C_G_E.2   ^|Compléter les champs et valider ^|Un nouvel employé est créé.  ^| aucune ^| OK

|====

|====

>|Cas de test 4+|Test-02-02-02
>|Titre 4+| Modifier un employé
>|Objectif 4+| Vérifier qu'il est possible de modifier un employé existant

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_E.3    ^|Cliquer sur le bouton "Modifier employé" ^|La fenêtre de modification d’employé s’ouvre avec les informations de l’employé selection ^|L’utilisateur est connecté en tant que chef d’agence

Un employé est sélectionné. ^| OK
^|C_G_E.4   ^|Modifier un ou plusieurs champ·s et valider ^|L’employé sélectionné a été modifié  ^| aucune ^| OK

|====

|====

>|Cas de test 4+|Test-02-02-03
>|Titre 4+| Affichage des employés
>|Objectif 4+| Vérifier qu'il est possible d’afficher la liste des employés

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_E.5    ^|Cliquer sur le bouton « Rechercher »  ^|La liste se remplit avec tous les employés de l’agence ^|L’utilisateur est connecté en tant que chef d’agence

Les champs de recherche sont vides.
^| OK
|====

|====

>|Cas de test 4+|Test-02-02-04
>|Titre 4+| Recherche d’un employé par son numéro
>|Objectif 4+| Vérifier qu'il est possible de rechercher un employé par son numéro

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_E.6    ^|Remplir le champ numéro avec le numéro d’un Employé existant.

Cliquer ensuite sur le bouton « Rechercher »  ^|La liste affiche l’employé recherché ^|L’utilisateur est connecté en tant que chef d’agence

L’employé saisi existe
^| OK
|====

|====

>|Cas de test 4+|Test-02-02-05
>|Titre 4+| Recherche d’employé par le début de leur nom prénom
>|Objectif 4+| Vérifier qu'il est possible de rechercher des employés par leurs noms et prénoms

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_E.7    ^|Remplir le champ nom avec le début du nom d’un employé et remplir le champ prénom avec le début du prénom de l’employé.

Cliquer ensuite sur le bouton « Rechercher »  ^|La liste affiche l’employé recherché ^|L’utilisateur est connecté en tant que chef d’agence

L’employé saisi existe
^| OK
|====

|====

>|Cas de test 4+|Test-02-02-06
>|Titre 4+| Supprimer un employé
>|Objectif 4+| Vérifier qu'il est possible de supprimer un employé existant

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_E.3    ^|Cliquer sur le bouton "Supprimer employé" ^|Une fenêtre de validation doit s’ouvrir^|L’utilisateur est connecté en tant que chef d’agence

Un employé est sélectionné. ^| OK
^|C_G_E.4   ^|Cliquer sur le bouton « Ok » ^|L’employé sélectionné a été modifié  ^| aucune ^| OK

|====

==== Débits exceptionnels

|====

>|Cas de test 4+|Test-02-03-01
>|Titre 4+| Ajouter un débit exceptionnel
>|Objectif 4+| Vérifier qu'il est possible de faire un débit exceptionnel

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_D_E.1    ^| Selectioner un compte et cliquer sur le bouton « Débit » ^|La fenêtre de création d’un débit s’ouvre  ^|L’utilisateur est connecté en tant que chef d’agence, le compte selectionné n’est pas cloturé ^| OK

^|C_D_E.2   ^|Compléter les champs avec un montant supérieur a la limite de découvert et valider ^|Une fenetre de confirmation s’ouvre ^| aucune ^| OK

^|C_D_E.3   ^|Cliquer sur le bouton « Ok » ^|Le débit est effectué en dépassant la limite de découvert du compte  ^| aucune ^| OK