@startgantt
!define t(x) <b>(x)

projectscale weekly zoom 2

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''',
'Taches
[Création du git t(1h30)] as [CreaGit] lasts 7 day
[Écriture du cahier des charges t(2h)] as [CDCU] lasts 10 day
[Création du Gantt t(2h)] as [GANTT] lasts 10 day

[Implémentation de la gestion des employé t(2h)] as [ImpleGest] lasts 10 day
[Rédaction des test de la gestion des employé t(45min)] as [TestGest] lasts 4 day
[Rédaction de la documentation technique de la gestion des employé t(45min)] as [DocGest] lasts 4 day

[Implémentation du crédit t(2h)] as [ImpleCred] lasts 10 day
[Rédaction des test du crédit t(45min)] as [TestCred] lasts 4 day
[Rédaction de la documentation technique du crédit t(45min)] as [DocCred] lasts 4 day

[Implémentation de la création de compte t(2h)] as [ImpleCrea] lasts 10 day
[Rédaction des test de la création de compte t(45min)] as [TestCrea] lasts 4 day
[Rédaction de la documentation technique de la création de compte t(45min)] as [DocCrea] lasts 4 day

[Implémentation des virements t(2h)] as [ImpleVir] lasts 10 day
[Rédaction des test des virements t(45min)] as [TestVir] lasts 4 day
[Rédaction de la documentation technique des virements t(45min)] as [DocVir] lasts 4 day

[Implémentation de la cloture des comptes t(2h)] as [ImpleClot] lasts 10 day
[Rédaction des test de la cloture des comptes t(45min)] as [TestClot] lasts 4 day
[Rédaction de la documentation technique de la cloture des comptes t(45min)] as [DocClot] lasts 4 day

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'Mise en ordre
[CDCU] starts at [CreaGit]'s end
[GANTT] starts at [CreaGit]'s end

[ImpleGest] starts at [CDCU]'s end
[TestGest] starts at [ImpleGest]'s end
[DocGest] starts at [ImpleGest]'s end

[ImpleCred] starts at [CDCU]'s end
[TestCred] starts at [ImpleCred]'s end
[DocCred] starts at [ImpleCred]'s end

[ImpleCrea] starts at [CDCU]'s end
[TestCrea] starts at [ImpleCrea]'s end
[DocCrea] starts at [ImpleCrea]'s end

[ImpleVir] starts at [CDCU]'s end
[TestVir] starts at [ImpleVir]'s end
[DocVir] starts at [ImpleVir]'s end

[ImpleClot] starts at [CDCU]'s end
[TestClot] starts at [ImpleClot]'s end
[DocClot] starts at [ImpleClot]'s end
@endgantt